version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRESDB_DATABASE}" , "-U", "${POSTGRESDB_USER}" ]
      interval : 5s
      timeout : 5s
      retries : 5
    networks:
      - private
    # ports:
    #   - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    build: .
    restart: unless-stopped
    env_file: ./.env
    networks:
      - public
      - private
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}
      - NODE_LOCAL_PORT=${NODE_LOCAL_PORT}
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  public:
  private: